export const ALL_BADGE_KEYS = [
  "rank_cadet", "rank_commando", "rank_seal", "rank_shadow", "rank_vanguard",
  "rank_sentinel", "rank_sovereign", "rank_warrior", "rank_architect",
  "rank_interceptor", "rank_phantom", "rank_cipher", "rank_crown",
  "sys_signin", "onb_claim_2x_day", "onb_claim_3x_consec",
  "hold_5", "hold_10", "hold_25", "hold_50", "hold_75", "hold_100",
  "sys_faucet", "fct_10", "fct_20", "fct_30", "fct_40", "fct_3day_row",
  "sys_tx_first", "tx_3", "tx_5", "sys_tx_10", "tx_25", "sys_tx_50",
  "tx_3_wallets", "tx_receive",
  "oc_first_swap", "oc_bridge_tokens", "oc_liquidity", "oc_nft_minter", "oc_multi_sig",
  "str_3day", "str_7day", "str_14day", "str_21day", "str_30day",
  "sys_email", "sys_discord", "sys_telegram", "sys_follow_x", "sys_x_follow",
  "soc_share_weekly", "soc_quote_weekly", "soc_screenshot", "soc_reply",
  "soc_tag_friend", "soc_retweet_launch",
  "soc_invite_1", "soc_squad", "soc_ambassador", "ref_25", "ref_50",
  "exp_faucet", "exp_leaderboard", "exp_badges", "exp_explorer",
  "sys_early_badge",
  "lb_top_500", "lb_top_100", "lb_top_50", "lb_top_10", "lb_climb_50", "lb_overtake_24h",
  "meta_first_badge", "meta_5_badges", "meta_10_badges", "meta_15_badges",
  "meta_all_categories", "meta_20_badges",
  "qe_500",
  "crate_1", "crate_5", "crate_10", "crate_25", "crate_50", "crate_100", "crate_150",
  "crate_5_in_day", "crate_streak_2", "crate_streak_7", "crate_streak_30", "crate_swap",
  "stake_qe_pool", "stake_daily_5", "stake_daily_14",
  "login_3_consec", "login_7_distinct", "login_14_distinct", "login_21_distinct", "login_30_distinct",
  "wk_claim_7", "wk_5_tx", "wk_share_x", "wk_refer_1", "wk_login_5",
] as const;
